### ISSUE TITLE
Optimize full re-index process

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#369]
On our latest production boxes a full re-index is problematic.  These are the issues that need to be addressed:
- [x] The indexer is slow.  It takes several days to index most of the distributions
- [ ] The indexer does not run to completion.  This may have been purely an issue with us running out of disk space, but obviously we'll want to ensure that it runs from start to finish
- [ ]  The logging output is too verbose.  There's a lot of info in the logs that doesn't seem to be helpful at all
- [ ] Archives are unpacked to a different location than the source files that the API serves up.  This means that we're actually keeping inflated 2 copies of most CPAN distributions, which is eating up a lot of space on disk.  There should be 1 location that the API and the indexer look to for inflated archives.  We can add an option to the indexer to wipe an archive out and then re-inflated it from scratch.  By default, we should not bother inflating if the code already exists on disk.
- [ ] There was an issue where the `backpan` flag was not being set correctly.
- [ ] Write some QA scripts in metacpan-qa that can be run after indexing to look for red flags

**Comment by tsibley** [comment]
What's the status of this in regards to the ES 2 / api v1 upgrade?

**Comment by ranguard** [comment]
@oalders I'd say we can close this?

**Comment by tsibley** [comment]
Or perhaps at least split up that checklist into separate issues.

**Comment by oalders** [comment]
Yes. Minion solved most of this. I think we're still inflating archives in two different places, but that's not really a pressing issue right now.  I'll close this.

**Comment by oalders** [comment]
@tsibley good idea.  I've moved the issue with archives to #538.
