### ISSUE TITLE
ES 2 Upgrade - Overview

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-api#408]
This ticket is to keep track of what's left and what we need help on.  The branch which we'll be working on to complete the work is at https://github.com/CPAN-API/cpan-api/tree/stage/lw-mc-03
# Blockers to going live with an upgraded ES
- [x] stage/lw-mc-03 has been rebased in order to bring in all changes from master.  There will be merge conflicts. (3 points)
- [x] Remove a lot of the garbage testing commits from this branch.  A lot of commits are in place purely for debugging purposes and they're just creating extra noise. (1 point)
- [x] Entire test suite is passing on VM (4 points)
- [x] Entire test suite is passing on Travis CI (1 point max if already passing on VM)
# Non-blocking TODO items
- [x] explorer.metacpan.org uses new API
- [ ] gh.metacpan.org uses new API
# QA
- [x] A branch off of metacpan-web exists using a stage/lw-mc-03 backend (1 point)
- [x] The metacpan-web branch passes all existing tests.  This dogfooding will essentially be our QA of the upgraded ES (4 points)
# Blockers to switching all traffic over to an upgraded ES
- [x] Indexing speed ( #369 ), now under 6 hours, but ticket has been reviewed (2 points)
- [x] The authors of MetaCPAN::Client have been notified of API v1 so that they can adjust accordingly.
- [ ] Tests assure that there are no disruptions to first class API consumers like `cpanm` and `rt.cpan.org`.  Some API consumers are listed here https://github.com/CPAN-API/cpan-api/wiki/API-Consumers
# Backwards Compatibility
- [x] A plan exists for how to run v0 and v1 cpan-api instances in parallel (1 point)
- [x] A schedule exists for the date when we will EOL v0
# Documentation

There was some talk of munging inbound and outbound data as a way to make v1 backwards compatible with v0.  Given the speed of this work in general, there's no point in doing this.  Let's get v1 up and running and then work to EOL v0. 
- [x] Some documentation exists for developers who wish to upgrade from v0 to v1
- [ ] Some documentation exists for the v1 API itself, which doesn't assume any knowledge of v0
# How to hack on this
## Check out the following repositories to the following branches:

cpan-api: stage/lw-mc-03
metacpan-puppet: es_2.2.0
metacpan-web: oalders/elasticsearch-2.0
## Carton install on VM

`sh /home/vagrant/bin/metacpan-api-carton install`
